/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e1e4",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary": "#ffbbbe",
        "surface": "#131315",
        "surface-container-lowest": "#0e0e10",
        "background": "#131315",
        "grid-line": "rgba(255, 255, 255, 0.03)",
        "on-secondary-fixed-variant": "#5516be",
        "outline": "#a08e7a",
        "zinc-outline": "#27272a",
        "tertiary-container": "#ff919a",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-background": "#e5e1e4",
        "inverse-surface": "#e5e1e4",
        "surface-variant": "#353437",
        "amber-glow": "rgba(245, 158, 11, 0.3)",
        "surface-dim": "#131315",
        "surface-container": "#201f22",
        "inverse-on-surface": "#313032",
        "on-primary-fixed-variant": "#653e00",
        "on-tertiary": "#67001b",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#92002a",
        "secondary-container": "#571bc1",
        "on-primary-fixed": "#2a1700",
        "surface-container-low": "#1c1b1d",
        "on-primary": "#472a00",
        "primary-fixed-dim": "#ffb95f",
        "outline-variant": "#534434",
        "on-secondary-container": "#c4abff",
        "inverse-primary": "#855300",
        "secondary": "#d0bcff",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdadb",
        "surface-tint": "#ffb95f",
        "secondary-fixed": "#e9ddff",
        "primary-container": "#f59e0b",
        "on-secondary-fixed": "#23005c",
        "surface-container-high": "#2a2a2c",
        "primary": "#ffc174",
        "on-secondary": "#3c0091",
        "tertiary-fixed-dim": "#ffb2b7",
        "primary-fixed": "#ffddb8",
        "on-tertiary-container": "#8c0028",
        "on-primary-container": "#613b00",
        "on-surface-variant": "#d8c3ad",
        "on-error": "#690005",
        "on-tertiary-fixed": "#40000d",
        "zinc-surface": "#18181b",
        "surface-bright": "#39393b",
        
        // Shadcn UI base colors mapping (fallback just in case)
        border: "#27272a",
        input: "#27272a",
        ring: "#ffc174",
        foreground: "#e5e1e4",
        card: "#18181b",
        "card-foreground": "#e5e1e4",
        popover: "#18181b",
        "popover-foreground": "#e5e1e4",
        muted: "#353437",
        "muted-foreground": "#a1a1aa",
        accent: "#ffb95f",
        "accent-foreground": "#472a00",
        destructive: "#ffb4ab",
        "destructive-foreground": "#690005",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1440px",
        "margin-mobile": "16px",
        "gutter-desktop": "24px",
        "unit": "4px",
        "margin-tablet": "32px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "mono-data": ["Space Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["15px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
